{  
  "openapi":"3.0.0",
  "info":{  
    "title":"LoopBack Application",
    "version":"1.0.0"
  },
  "paths":{  
    "/heroes/count":{  
      "get":{  
        "x-controller-name":"HeroController",
        "x-operation-name":"count",
        "tags":[  
          "HeroController"
        ],
        "responses":{  
          "200":{  
            "description":"Hero model count",
            "content":{  
              "application/json":{  
                "schema":{  
                  "type":"object",
                  "properties":{  
                    "count":{  
                      "type":"number"
                    }
                  }
                }
              }
            }
          }
        },
        "parameters":[  
          {  
            "name":"where",
            "in":"query",
            "style":"deepObject",
            "explode":true,
            "schema":{  
              "type":"object"
            }
          }
        ]
      }
    },
    "/heroes/{id}":{  
      "patch":{  
        "x-controller-name":"HeroController",
        "x-operation-name":"updateById",
        "tags":[  
          "HeroController"
        ],
        "responses":{  
          "204":{  
            "description":"Hero PATCH success"
          }
        },
        "parameters":[  
          {  
            "name":"id",
            "in":"path",
            "schema":{  
              "type":"string"
            },
            "required":true
          }
        ],
        "requestBody":{  
          "content":{  
            "application/json":{  
              "schema":{  
                "$ref":"#/components/schemas/Hero"
              }
            }
          },
          "x-parameter-index":1
        }
      },
      "get":{  
        "x-controller-name":"HeroController",
        "x-operation-name":"findById",
        "tags":[  
          "HeroController"
        ],
        "responses":{  
          "200":{  
            "description":"Hero model instance",
            "content":{  
              "application/json":{  
                "schema":{  
                  "$ref":"#/components/schemas/Hero"
                }
              }
            }
          }
        },
        "parameters":[  
          {  
            "name":"id",
            "in":"path",
            "schema":{  
              "type":"string"
            },
            "required":true
          }
        ]
      },
      "delete":{  
        "x-controller-name":"HeroController",
        "x-operation-name":"deleteById",
        "tags":[  
          "HeroController"
        ],
        "responses":{  
          "204":{  
            "description":"Hero DELETE success"
          }
        },
        "parameters":[  
          {  
            "name":"id",
            "in":"path",
            "schema":{  
              "type":"string"
            },
            "required":true
          }
        ]
      }
    },
    "/heroes":{  
      "post":{  
        "x-controller-name":"HeroController",
        "x-operation-name":"create",
        "tags":[  
          "HeroController"
        ],
        "responses":{  
          "200":{  
            "description":"Hero model instance",
            "content":{  
              "application/json":{  
                "schema":{  
                  "$ref":"#/components/schemas/Hero"
                }
              }
            }
          }
        },
        "requestBody":{  
          "content":{  
            "application/json":{  
              "schema":{  
                "$ref":"#/components/schemas/Hero"
              }
            }
          }
        }
      },
      "patch":{  
        "x-controller-name":"HeroController",
        "x-operation-name":"updateAll",
        "tags":[  
          "HeroController"
        ],
        "responses":{  
          "200":{  
            "description":"Hero PATCH success count",
            "content":{  
              "application/json":{  
                "schema":{  
                  "type":"object",
                  "properties":{  
                    "count":{  
                      "type":"number"
                    }
                  }
                }
              }
            }
          }
        },
        "parameters":[  
          {  
            "name":"where",
            "in":"query",
            "style":"deepObject",
            "explode":true,
            "schema":{  
              "type":"object"
            }
          }
        ],
        "requestBody":{  
          "content":{  
            "application/json":{  
              "schema":{  
                "$ref":"#/components/schemas/Hero"
              }
            }
          }
        }
      },
      "get":{  
        "x-controller-name":"HeroController",
        "x-operation-name":"find",
        "tags":[  
          "HeroController"
        ],
        "responses":{  
          "200":{  
            "description":"Array of Hero model instances",
            "content":{  
              "application/json":{  
                "schema":{  
                  "type":"array",
                  "items":{  
                    "$ref":"#/components/schemas/Hero"
                  }
                }
              }
            }
          }
        },
        "parameters":[  
          {  
            "name":"filter",
            "in":"query",
            "style":"deepObject",
            "explode":true,
            "schema":{  
              "properties":{  
                "where":{  
                  "type":"object"
                },
                "fields":{  
                  "type":"object"
                },
                "offset":{  
                  "type":"integer",
                  "minimum":0
                },
                "limit":{  
                  "type":"integer",
                  "minimum":0
                },
                "skip":{  
                  "type":"integer",
                  "minimum":0
                },
                "order":{  
                  "type":"array",
                  "items":{  
                    "type":"string"
                  }
                },
                "include":{  
                  "type":"array",
                  "items":{  
                    "type":"object",
                    "properties":{  
                      "relation":{  
                        "type":"string"
                      },
                      "scope":{  
                        "properties":{  
                          "where":{  
                            "type":"object"
                          },
                          "fields":{  
                            "type":"object"
                          },
                          "offset":{  
                            "type":"integer",
                            "minimum":0
                          },
                          "limit":{  
                            "type":"integer",
                            "minimum":0
                          },
                          "skip":{  
                            "type":"integer",
                            "minimum":0
                          },
                          "order":{  
                            "type":"array",
                            "items":{  
                              "type":"string"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              },
              "type":"object"
            }
          }
        ]
      }
    },
    "/species/count":{  
      "get":{  
        "x-controller-name":"SpeciesController",
        "x-operation-name":"count",
        "tags":[  
          "SpeciesController"
        ],
        "responses":{  
          "200":{  
            "description":"Species model count",
            "content":{  
              "application/json":{  
                "schema":{  
                  "type":"object",
                  "properties":{  
                    "count":{  
                      "type":"number"
                    }
                  }
                }
              }
            }
          }
        },
        "parameters":[  
          {  
            "name":"where",
            "in":"query",
            "style":"deepObject",
            "explode":true,
            "schema":{  
              "type":"object"
            }
          }
        ]
      }
    },
    "/species/{id}":{  
      "patch":{  
        "x-controller-name":"SpeciesController",
        "x-operation-name":"updateById",
        "tags":[  
          "SpeciesController"
        ],
        "responses":{  
          "204":{  
            "description":"Species PATCH success"
          }
        },
        "parameters":[  
          {  
            "name":"id",
            "in":"path",
            "schema":{  
              "type":"string"
            },
            "required":true
          }
        ],
        "requestBody":{  
          "content":{  
            "application/json":{  
              "schema":{  
                "$ref":"#/components/schemas/Species"
              }
            }
          },
          "x-parameter-index":1
        }
      },
      "get":{  
        "x-controller-name":"SpeciesController",
        "x-operation-name":"findById",
        "tags":[  
          "SpeciesController"
        ],
        "responses":{  
          "200":{  
            "description":"Species model instance",
            "content":{  
              "application/json":{  
                "schema":{  
                  "$ref":"#/components/schemas/Species"
                }
              }
            }
          }
        },
        "parameters":[  
          {  
            "name":"id",
            "in":"path",
            "schema":{  
              "type":"string"
            },
            "required":true
          }
        ]
      },
      "delete":{  
        "x-controller-name":"SpeciesController",
        "x-operation-name":"deleteById",
        "tags":[  
          "SpeciesController"
        ],
        "responses":{  
          "204":{  
            "description":"Species DELETE success"
          }
        },
        "parameters":[  
          {  
            "name":"id",
            "in":"path",
            "schema":{  
              "type":"string"
            },
            "required":true
          }
        ]
      }
    },
    "/species":{  
      "post":{  
        "x-controller-name":"SpeciesController",
        "x-operation-name":"create",
        "tags":[  
          "SpeciesController"
        ],
        "responses":{  
          "200":{  
            "description":"Species model instance",
            "content":{  
              "application/json":{  
                "schema":{  
                  "$ref":"#/components/schemas/Species"
                }
              }
            }
          }
        },
        "requestBody":{  
          "content":{  
            "application/json":{  
              "schema":{  
                "$ref":"#/components/schemas/Species"
              }
            }
          }
        }
      },
      "patch":{  
        "x-controller-name":"SpeciesController",
        "x-operation-name":"updateAll",
        "tags":[  
          "SpeciesController"
        ],
        "responses":{  
          "200":{  
            "description":"Species PATCH success count",
            "content":{  
              "application/json":{  
                "schema":{  
                  "type":"object",
                  "properties":{  
                    "count":{  
                      "type":"number"
                    }
                  }
                }
              }
            }
          }
        },
        "parameters":[  
          {  
            "name":"where",
            "in":"query",
            "style":"deepObject",
            "explode":true,
            "schema":{  
              "type":"object"
            }
          }
        ],
        "requestBody":{  
          "content":{  
            "application/json":{  
              "schema":{  
                "$ref":"#/components/schemas/Species"
              }
            }
          }
        }
      },
      "get":{  
        "x-controller-name":"SpeciesController",
        "x-operation-name":"find",
        "tags":[  
          "SpeciesController"
        ],
        "responses":{  
          "200":{  
            "description":"Array of Species model instances",
            "content":{  
              "application/json":{  
                "schema":{  
                  "type":"array",
                  "items":{  
                    "$ref":"#/components/schemas/Species"
                  }
                }
              }
            }
          }
        },
        "parameters":[  
          {  
            "name":"filter",
            "in":"query",
            "style":"deepObject",
            "explode":true,
            "schema":{  
              "properties":{  
                "where":{  
                  "type":"object"
                },
                "fields":{  
                  "type":"object"
                },
                "offset":{  
                  "type":"integer",
                  "minimum":0
                },
                "limit":{  
                  "type":"integer",
                  "minimum":0
                },
                "skip":{  
                  "type":"integer",
                  "minimum":0
                },
                "order":{  
                  "type":"array",
                  "items":{  
                    "type":"string"
                  }
                },
                "include":{  
                  "type":"array",
                  "items":{  
                    "type":"object",
                    "properties":{  
                      "relation":{  
                        "type":"string"
                      },
                      "scope":{  
                        "properties":{  
                          "where":{  
                            "type":"object"
                          },
                          "fields":{  
                            "type":"object"
                          },
                          "offset":{  
                            "type":"integer",
                            "minimum":0
                          },
                          "limit":{  
                            "type":"integer",
                            "minimum":0
                          },
                          "skip":{  
                            "type":"integer",
                            "minimum":0
                          },
                          "order":{  
                            "type":"array",
                            "items":{  
                              "type":"string"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              },
              "type":"object"
            }
          }
        ]
      }
    }
  },
  "servers":[  
    {  
      "url":"http://127.0.0.1:3000"
    }
  ],
  "components":{  
    "schemas":{  
      "Species":{  
        "title":"Species",
        "properties":{  
          "id":{  
            "type":"number",
            "description":"Species id"
          },
          "name":{  
            "type":"string",
            "description":"The species name"
          },
          "planet":{  
            "type":"string",
            "description":"The planet the species is from"
          },
          "lifespan":{  
            "type":"number",
            "description":"The lifespan of the species"
          },
          "heroId":{  
            "type":"number"
          }
        }
      },
      "Hero":{  
        "title":"Hero",
        "properties":{  
          "id":{  
            "type":"number",
            "description":"Hero id"
          },
          "name":{  
            "type":"string",
            "description":"The heroes' name"
          },
          "hasSuperPowers":{  
            "type":"boolean",
            "description":"Hero has super powers"
          },
          "species":{  
            "type":"array",
            "items":{  
              "$ref":"#/components/schemas/Species"
            }
          }
        }
      }
    }
  }
}
